SHELL := bash

.PHONY: all build_shock identity_check immediate_run immediate_summary tiny_smoke clean

all build_shock identity_check immediate_run immediate_summary tiny_smoke clean:
	$(MAKE) -C code $@
